#!/usr/bin/env node
// Read `dist/pii.wasm` and emit `src/js/backends/pii-wasm-inline.ts`
// containing the bytes as a Uint8Array literal. Called between
// `build:zig` (+ `build:opt`) and `build`.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const WASM = join(REPO, "dist", "pii.wasm");
const OUT = join(REPO, "src", "js", "backends", "pii-wasm-inline.ts");

const bytes = await readFile(WASM);
const hex = Array.from(bytes).map((b) => `0x${b.toString(16).padStart(2, "0")}`);
const chunks = [];
for (let i = 0; i < hex.length; i += 16) {
  chunks.push("  " + hex.slice(i, i + 16).join(", ") + ",");
}
const content =
  `// AUTO-GENERATED by scripts/inline-wasm.mjs. Do not edit.\n` +
  `// Size: ${bytes.length} bytes. Regenerate after \`npm run build:zig\`.\n\n` +
  `export const PII_WASM_BYTES: Uint8Array = new Uint8Array([\n` +
  chunks.join("\n") +
  `\n]);\n`;
await writeFile(OUT, content, "utf8");
console.log(`inline-wasm: wrote ${OUT}  (${bytes.length} bytes → ${hex.length * 6}-ish source chars)`);
