#!/usr/bin/env node
// Read `dist/pii.wasm` (single-thread) and `dist/pii-mt.wasm`
// (shared-memory + atomics, for multi-thread workers) and emit
// `src/js/backends/pii-wasm-inline.ts` containing both as Uint8Array
// literals. Called between `build:zig` (+ `build:opt`) and `build`.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const ST = join(REPO, "dist", "pii.wasm");
const MT = join(REPO, "dist", "pii-mt.wasm");
const OUT = join(REPO, "src", "js", "backends", "pii-wasm-inline.ts");

function emit(name, bytes) {
  const hex = Array.from(bytes).map((b) => `0x${b.toString(16).padStart(2, "0")}`);
  const chunks = [];
  for (let i = 0; i < hex.length; i += 16) {
    chunks.push("  " + hex.slice(i, i + 16).join(", ") + ",");
  }
  return (
    `export const ${name}: Uint8Array = new Uint8Array([\n` +
    chunks.join("\n") +
    `\n]);\n`
  );
}

const stBytes = await readFile(ST);
const mtBytes = await readFile(MT);

const content =
  `// AUTO-GENERATED by scripts/inline-wasm.mjs. Do not edit.\n` +
  `// pii.wasm   (single-thread): ${stBytes.length} bytes\n` +
  `// pii-mt.wasm (shared-memory + atomics): ${mtBytes.length} bytes\n` +
  `// Regenerate after \`npm run build:zig\`.\n\n` +
  emit("PII_WASM_BYTES", stBytes) +
  `\n` +
  emit("PII_WASM_MT_BYTES", mtBytes);

await writeFile(OUT, content, "utf8");
console.log(
  `inline-wasm: wrote ${OUT}  ` +
    `(st=${stBytes.length}b, mt=${mtBytes.length}b)`,
);
