#!/usr/bin/env node
// One-shot extraction: pull every `const X_WGSL = /* wgsl */ \`...\`;`
// block out of `src/browser/backends/webgpu.ts` into individual
// `src/shaders/<lowercase_name>.wgsl` files. Resolves the
// `${INT4_ACCESS_WGSL}` template substitution by inlining the helper
// at the marker. After extraction, `webgpu.ts` is rewritten to
// import each shader from a generated `shaders.ts` that re-exports
// the contents of every .wgsl file.
//
// Single source of truth: the .wgsl files. Both the browser bundle
// (via shaders.ts) and the native Zig binding (via @embedFile) read
// from the same place.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const WEBGPU = join(REPO, "src", "browser", "backends", "webgpu.ts");
const SHADERS_DIR = join(REPO, "src", "native", "shaders");
const SHADERS_TS = join(REPO, "src", "browser", "backends", "shaders.ts");

await mkdir(SHADERS_DIR, { recursive: true });

const src = await readFile(WEBGPU, "utf8");

// Match: const NAME_WGSL = /* wgsl */ `...`;
// The body may contain backticks-in-strings, but our shaders don't,
// so a non-greedy match between the wrapping backticks works.
const blockRe = /const\s+([A-Z_0-9]+_WGSL)\s*=\s*\/\*\s*wgsl\s*\*\/\s*`([\s\S]*?)`\s*;/g;

const blocks = [];
let match;
while ((match = blockRe.exec(src)) !== null) {
  blocks.push({ name: match[1], body: match[2], start: match.index, end: match.index + match[0].length });
}

if (blocks.length === 0) {
  console.error("no WGSL blocks found");
  process.exit(1);
}

// Build a name → body map for include resolution.
const nameToBody = Object.fromEntries(blocks.map((b) => [b.name, b.body]));

// Write each .wgsl file with `${OTHER_WGSL}` substitutions resolved.
for (const block of blocks) {
  let body = block.body;
  // Resolve any ${NAME_WGSL} templates by inlining the referenced body.
  body = body.replace(/\$\{([A-Z_0-9]+_WGSL)\}/g, (_, name) => {
    if (!nameToBody[name]) {
      throw new Error(`unresolved include: ${name} (referenced by ${block.name})`);
    }
    return nameToBody[name];
  });
  // Trim leading/trailing blank line that came from the template literal.
  if (body.startsWith("\n")) body = body.slice(1);
  if (!body.endsWith("\n")) body += "\n";

  const fname = block.name.toLowerCase().replace(/_wgsl$/, "") + ".wgsl";
  await writeFile(join(SHADERS_DIR, fname), body, "utf8");
  console.log(`  wrote src/native/shaders/${fname}  (${body.length} bytes)`);
}

// Generate shaders.ts that re-exports each .wgsl as a string constant.
// Browser webgpu.ts imports from here; native Zig @embedFile reads
// the .wgsl files directly.
let tsOut = "// AUTO-GENERATED by scripts/extract-shaders.mjs.\n";
tsOut += "// Source of truth: ../../native/shaders/*.wgsl\n";
tsOut += "// Re-running the script regenerates this file from the .wgsl sources.\n\n";
for (const block of blocks) {
  const fname = block.name.toLowerCase().replace(/_wgsl$/, "") + ".wgsl";
  const ident = block.name;
  const body = await readFile(join(SHADERS_DIR, fname), "utf8");
  tsOut += `export const ${ident}: string = ${JSON.stringify(body)};\n\n`;
}
await writeFile(SHADERS_TS, tsOut, "utf8");
console.log(`  wrote src/browser/backends/shaders.ts  (${tsOut.length} bytes)`);

// Rewrite webgpu.ts: replace each `const X_WGSL = /* wgsl */ \`...\`;`
// block with an import. Multi-shader import lives at the top.
const importLines = ["import {", ...blocks.map((b) => `  ${b.name},`), '} from "./shaders.js";'].join("\n");

let out = src;
// Remove all the original blocks (in reverse so offsets stay valid).
for (const block of [...blocks].reverse()) {
  out = out.slice(0, block.start) + out.slice(block.end);
}
// Inject the import after the first existing import (keep imports grouped at top).
const firstImportEnd = out.match(/^import[\s\S]*?from\s+"[^"]+";\s*\n/m);
if (!firstImportEnd) {
  // No imports at all — prepend.
  out = importLines + "\n\n" + out;
} else {
  const insertAt = firstImportEnd.index + firstImportEnd[0].length;
  out = out.slice(0, insertAt) + importLines + "\n" + out.slice(insertAt);
}

await writeFile(WEBGPU, out, "utf8");
console.log(`  rewrote ${WEBGPU}  (${blocks.length} shader imports inlined)`);
