#!/usr/bin/env node
// Read `dist/browser/textsift.wasm` (single-thread) and
// `dist/browser/textsift-mt.wasm` (shared-memory + atomics, for
// multi-thread workers) and emit
// `src/browser/backends/textsift-inline.ts` containing both as
// Uint8Array literals. Called between `build:zig` (+ `build:opt`)
// and `build:browser`.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const ST = join(REPO, "dist", "browser", "textsift.wasm");
const MT = join(REPO, "dist", "browser", "textsift-mt.wasm");
const OUT = join(REPO, "src", "browser", "backends", "textsift-inline.ts");

function emit(name, bytes) {
  const hex = Array.from(bytes).map((b) => `0x${b.toString(16).padStart(2, "0")}`);
  const chunks = [];
  for (let i = 0; i < hex.length; i += 16) {
    chunks.push("  " + hex.slice(i, i + 16).join(", ") + ",");
  }
  return (
    `export const ${name}: Uint8Array = new Uint8Array([\n` +
    chunks.join("\n") +
    `\n]);\n`
  );
}

const stBytes = await readFile(ST);
const mtBytes = await readFile(MT);

const content =
  `// AUTO-GENERATED by scripts/inline-wasm.mjs. Do not edit.\n` +
  `// textsift.wasm   (single-thread): ${stBytes.length} bytes\n` +
  `// textsift-mt.wasm (shared-memory + atomics): ${mtBytes.length} bytes\n` +
  `// Regenerate after \`npm run build:zig\`.\n\n` +
  emit("TEXTSIFT_BYTES", stBytes) +
  `\n` +
  emit("TEXTSIFT_MT_BYTES", mtBytes);

await writeFile(OUT, content, "utf8");
console.log(
  `inline-wasm: wrote ${OUT}  ` +
    `(st=${stBytes.length}b, mt=${mtBytes.length}b)`,
);
